# App Engine configuration for Tri-Netra (if deploying to App Engine)
runtime: python312

# Instance configuration
instance_class: F2

# Environment variables
env_variables:
  FRAUD_AMOUNT_THRESHOLD: "10000.0"
  BUSINESS_RULES_ENABLED: "true"
  TRI_NETRA_MODEL: "gemini-2.0-flash-exp"
  ANALYSIS_MODEL: "gemini-2.0-flash-exp"
  LOG_LEVEL: "INFO"

# Handlers
handlers:
  - url: /.*
    script: auto
    secure: always

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
